### ISSUE TITLE
change in layout: width

### ISSUE THREAD

**Issue by ManuLinares** [blyad2137/dark-instagram--variable-recolor--forked#3]
add these:

```
    ._8GFVD {
        max-width: calc(470px + /*[[feed]]*/)!important;
    }
    .N2s2W {
        max-width: calc(470px + /*[[feed]]*/)!important;
    }
```

**Comment by blyad2137** [comment]
Thats some JS bullshit, what do those lines change and where?
Everything seems centered

**Comment by ManuLinares** [comment]
JS bullshit? I don't understand what you mean. This is css, same as [this](https://github.com/blyad2137/dark-instagram--variable-recolor--forked/blob/55b302f22df43fbd6a4a97cada6d7b59b8f2e07a/dark-instagram-variable-recolor-forked.user.css#L579)

Let me give you a better **description of the problem:**

"When configuring the size of the feed for example to 75%, the width of the feed stays small"

Proposed Solution: update the css, like I mentioned above or with other means. I just opened dev tools and found those two classes, and with those options it works as intended

**Comment by blyad2137** [comment]
I meant the name of elements, I can't tell what they were suppose to mean, because they were generated via JS.

And the problem is that those elements are nowhere to be found.
![image](https://user-images.githubusercontent.com/86572965/197997506-96116399-f2dc-406c-a63a-1b4cec6b0771.png)
(1 of 1 shows because it detects the usercss for some reason)
